<footer class="d-flex flex-column align-items-center">
    <h2>Say Hello.</h2>
    <a href="mailto:nhobedoza@gmail.com" class="mb-2">noemyobedoza@gmail.com</a>
    <div class="d-flex contacts mb-4">
        <a href="tel:+639087300550">Phone</a>
        <a href="https://wa.me/+639087300550">Whatsapp</a>
        <a href="tg://resolve?domain=nhobedoza30">Telegram</a>
    </div>
    <small>&copy;2022 Scorpbytes PH Ltd.</small>
</footer>